{% set name = "zdesk" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zdesk-{{ version }}.tar.gz
  sha256: 9979be43469c577da14018f3cd3c2182962e17aa55cb9415269a3ce27b674ca5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.0
  run:
    - python >=3.0
    - requests
    - six

test:
  imports:
    - zdesk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fprimex/zdesk
  summary: Zendesk API generated directly from developer.zendesk.com
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://github.com/fprimex/zdesk
  dev_url: https://github.com/fprimex/zdesk

extra:
  recipe-maintainers:
    - xylar
